import type { Frame } from "@/types/frame";

/**
 * PLACEHOLDER catalog. Brands are fictional. Replace with your in-store range —
 * the 3D viewer and card silhouettes are generated from shape, material, colour and
 * measurements, so a new entry needs no images or 3D files to display.
 */
export const frames: Frame[] = [
  {
    slug: "aurora-round",
    name: "Aurora",
    brand: "Lumen",
    kind: "eyeglasses",
    shape: "round",
    material: "metal",
    gender: "unisex",
    rim: "full",
    priceINR: 2490,
    colors: [
      { name: "Gold", hex: "#c9a45c" },
      { name: "Silver", hex: "#c3c7cc" },
      { name: "Matte Black", hex: "#2a2b2e", finish: "matte" },
    ],
    measurements: { lensWidth: 49, lensHeight: 46, bridge: 20, templeLength: 145 },
    description: "A thin-wire round frame with adjustable nose pads. Light enough to forget you're wearing it.",
    featured: true,
  },
  {
    slug: "mira-cat-eye",
    name: "Mira",
    brand: "Aria",
    kind: "eyeglasses",
    shape: "cat-eye",
    material: "acetate",
    gender: "women",
    rim: "full",
    priceINR: 2990,
    colors: [
      { name: "Havana Tortoise", hex: "#3a1f0e", pattern: "tortoise" },
      { name: "Gloss Black", hex: "#151517" },
      { name: "Rose Crystal", hex: "#e8b4b8", pattern: "crystal" },
    ],
    measurements: { lensWidth: 52, lensHeight: 42, bridge: 17, templeLength: 140 },
    description: "Hand-polished acetate with a lifted outer corner — soft enough for everyday, sharp enough to notice.",
    featured: true,
  },
  {
    slug: "kestrel-aviator",
    name: "Kestrel",
    brand: "Northline",
    kind: "sunglasses",
    shape: "aviator",
    material: "metal",
    gender: "men",
    rim: "full",
    priceINR: 3990,
    lensTint: "#2f3a2c",
    colors: [
      { name: "Gunmetal", hex: "#4a4d52" },
      { name: "Gold", hex: "#c9a45c" },
    ],
    measurements: { lensWidth: 58, lensHeight: 50, bridge: 15, templeLength: 140 },
    description: "Classic double-bridge aviator with polarised UV400 lenses. Built for Indian summers.",
    featured: true,
  },
  {
    slug: "atlas-rectangle",
    name: "Atlas",
    brand: "Power Eyes Signature",
    kind: "eyeglasses",
    shape: "rectangle",
    material: "tr90",
    gender: "men",
    rim: "full",
    priceINR: 1490,
    colors: [
      { name: "Matte Black", hex: "#1f2023", finish: "matte" },
      { name: "Navy", hex: "#1f2d4a", finish: "matte" },
    ],
    measurements: { lensWidth: 55, lensHeight: 38, bridge: 18, templeLength: 145 },
    description: "Flexible TR90 that bends back into shape. An office-to-weekend workhorse.",
  },
  {
    slug: "noor-oval",
    name: "Noor",
    brand: "Aria",
    kind: "eyeglasses",
    shape: "oval",
    material: "titanium",
    gender: "women",
    rim: "half",
    priceINR: 5490,
    colors: [
      { name: "Rose Gold", hex: "#d4a08a" },
      { name: "Champagne", hex: "#d9c9a3" },
    ],
    measurements: { lensWidth: 51, lensHeight: 36, bridge: 18, templeLength: 140 },
    description: "Half-rim pure titanium. Hypoallergenic, featherweight and quietly elegant.",
    featured: true,
  },
  {
    slug: "vega-wayfarer",
    name: "Vega",
    brand: "Kestrel & Co.",
    kind: "eyeglasses",
    shape: "wayfarer",
    material: "acetate",
    gender: "unisex",
    rim: "full",
    priceINR: 2290,
    colors: [
      { name: "Gloss Black", hex: "#141416" },
      { name: "Amber Tortoise", hex: "#4a2a12", pattern: "tortoise" },
    ],
    measurements: { lensWidth: 52, lensHeight: 40, bridge: 19, templeLength: 145 },
    description: "The shape that suits almost everyone, in thick Italian-style acetate.",
  },
  {
    slug: "hex-titanium",
    name: "Hexa",
    brand: "Lumen",
    kind: "eyeglasses",
    shape: "hexagon",
    material: "titanium",
    gender: "unisex",
    rim: "full",
    priceINR: 6490,
    colors: [
      { name: "Silver", hex: "#c3c7cc" },
      { name: "Gold", hex: "#c9a45c" },
    ],
    measurements: { lensWidth: 50, lensHeight: 44, bridge: 20, templeLength: 145 },
    description: "Geometric titanium with a brushed finish. Distinctive without being loud.",
  },
  {
    slug: "pixie-kids-round",
    name: "Pixie",
    brand: "Power Eyes Kids",
    kind: "eyeglasses",
    shape: "round",
    material: "tr90",
    gender: "kids",
    rim: "full",
    priceINR: 990,
    colors: [
      { name: "Ocean Blue", hex: "#2f6fb5" },
      { name: "Bubblegum", hex: "#e87fa7" },
    ],
    measurements: { lensWidth: 44, lensHeight: 40, bridge: 16, templeLength: 125 },
    description: "Near-unbreakable TR90 for ages 5–10. Survives school bags and cricket.",
  },
  {
    slug: "orion-square",
    name: "Orion",
    brand: "Northline",
    kind: "eyeglasses",
    shape: "square",
    material: "acetate",
    gender: "men",
    rim: "full",
    priceINR: 2790,
    colors: [
      { name: "Crystal Clear", hex: "#dfe6ea", pattern: "crystal" },
      { name: "Dark Tortoise", hex: "#2c170a", pattern: "tortoise" },
    ],
    measurements: { lensWidth: 53, lensHeight: 46, bridge: 18, templeLength: 145 },
    description: "Bold square acetate with a keyhole-free flat bridge. Makes a statement.",
    featured: true,
  },
  {
    slug: "sahara-cat-eye-sun",
    name: "Sahara",
    brand: "Aria",
    kind: "sunglasses",
    shape: "cat-eye",
    material: "acetate",
    gender: "women",
    rim: "full",
    priceINR: 3490,
    lensTint: "#3b2a1c",
    colors: [
      { name: "Honey Tortoise", hex: "#5a3312", pattern: "tortoise" },
      { name: "Ivory", hex: "#efe6d4" },
    ],
    measurements: { lensWidth: 55, lensHeight: 46, bridge: 16, templeLength: 140 },
    description: "Oversized cat-eye sunglasses with gradient brown UV400 lenses.",
  },
  {
    slug: "slate-half-rim",
    name: "Slate",
    brand: "Power Eyes Signature",
    kind: "eyeglasses",
    shape: "rectangle",
    material: "metal",
    gender: "men",
    rim: "half",
    priceINR: 3290,
    colors: [
      { name: "Gunmetal", hex: "#4a4d52" },
      { name: "Black", hex: "#222326", finish: "matte" },
    ],
    measurements: { lensWidth: 54, lensHeight: 34, bridge: 17, templeLength: 145 },
    description: "Half-rim metal with a clean browline. Professional, light and easy to wear all day.",
  },
  {
    slug: "bloom-kids-oval",
    name: "Bloom",
    brand: "Power Eyes Kids",
    kind: "eyeglasses",
    shape: "oval",
    material: "acetate",
    gender: "kids",
    rim: "full",
    priceINR: 1190,
    colors: [
      { name: "Lilac", hex: "#b59ad6" },
      { name: "Mint", hex: "#8fcfb6" },
    ],
    measurements: { lensWidth: 45, lensHeight: 36, bridge: 15, templeLength: 125 },
    description: "Soft-edged acetate in cheerful colours, with spring hinges for a snug fit.",
  },
];
